<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-AdminPortal-5e1419e1-6e03-4854-97c8-d021347a2efc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Audit.EntityFramework.Core" Version="32.0.0" />
    <PackageReference Include="Audit.EntityFramework.Identity.Core" Version="32.0.0" />
    <PackageReference Include="Audit.Mvc.Core" Version="32.0.0" />
    <PackageReference Include="Humanizer" Version="3.0.1" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="X.PagedList.EF" Version="10.5.9" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="10.5.9" />
  </ItemGroup>

</Project>
